# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       pacrunner
Summary:    Proxy configuration dæmon
Version:    0.4
Release:    3
Group:      System/Networking
License:    GPLv2
URL:        http://connman.net/
Source0:    http://www.kernel.org/pub/linux/network/connman/pacrunner-%{version}.tar.xz
Source1:    libproxy.py
Source100:  pacrunner.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(libcurl)
BuildRequires:  python
BuildRequires:  v8-devel
BuildRequires:  pkgconfig(gthread-2.0)
Provides:   libproxy
Obsoletes:   libproxy < 0.5


%description
PacRunner provides a dæmon for processing proxy configuration
and providing information to clients over D-Bus.



%package python
Summary:    Python lib for PacRunner
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   pacrunner
Provides:   libproxy-python
Obsoletes:   libproxy-python < 0.5

%description python
A python library for proxy configuration and autodetection

%package devel
Summary:    Development files for PacRunner
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Provides:   libproxy-devel
Obsoletes:   libproxy-devel < 0.5

%description devel
This provides the development files for building against
pacrunner's implementation of libproxy



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
autoreconf --force --install
# << build pre

%configure --disable-static \
    --enable-libproxy \
    --enable-curl \
    --disable-capng \
    --enable-datafiles \
    --enable-v8

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mv $RPM_BUILD_ROOT/%{_datadir}/dbus-1/system-services/{,org.}pacrunner.service
mkdir -p ${RPM_BUILD_ROOT}/%{python_sitelib}
install -m0644 %{SOURCE1} $RPM_BUILD_ROOT/%{python_sitelib}/libproxy.py
rm -f $RPM_BUILD_ROOT/%{_libdir}/libproxy.la
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig








%files
%defattr(-,root,root,-)
# >> files
%doc COPYING README COPYING.LIB AUTHORS ChangeLog
%{_sbindir}/pacrunner
%{_libdir}/libproxy.so.1.0.0
%{_libdir}/libproxy.so.1
%{_bindir}/proxy
%{_datadir}/dbus-1/system-services/org.pacrunner.service
%config %{_sysconfdir}/dbus-1/system.d/pacrunner.conf
# << files


%files python
%defattr(-,root,root,-)
# >> files python
%{python_sitelib}/libproxy.py*
# << files python

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libproxy.so
%{_includedir}/proxy.h
%{_libdir}/pkgconfig/libproxy-1.0.pc
# << files devel

